name: serialization_task
description: Serialization and deserialization task
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  yaml: ^3.1.2
  toml: ^0.15.0

dev_dependencies:
  lints: ^3.0.0
